server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?allowMultiQueries=true
    username: root
    password: 103317
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.163.com
    username: Ljj1033173808@163.com
    password: TCNPDGZTJBCMALKG
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

qiniu:
  accessKey: 3w4hJ4HOK_ECJI08hUyOKhAXKAgwQTQen4cKHrip
  secretKey: FwghmLM9QogJOhRYl5-Fr_Y4BoIchgH6YPVEn0YR
  bucketName: nshj-shop
  path: http://cdn.mynshj.top/
  directory: shop/





