spring:
  datasource:  #配置mysql数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 103317
    type: com.alibaba.druid.pool.DruidDataSource
  data: #配置redis数据库
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
  mail: #配置邮箱服务
    host: smtp.163.com
    username: Ljj1033173808@163.com
    password: TCNPDGZTJBCMALKG
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true

mybatis:      #配置mybatis
  configuration:
    map-underscore-to-camel-case: true

